filepath = "calculator-engine.js"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

start_marker = "  const APPLIANCES = ["
end_marker = "  ];\n\n  function calculateSolarResults"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx != -1 and end_idx != -1:
    new_appliances = """  const APPLIANCES = [
    { id: "window_ac", property_type: "residential", category: "HVAC", name_en: "Window AC", name_ar: "مكيف نافذة", min_w: 1500, max_w: 2000, hours: 8.0, default_qty: 0, desc_en: "Standard window-mounted room cooler", desc_ar: "وحدة تبريد الغرفة القياسية المثبتة على النافذة", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "ac_1ton", property_type: "residential", category: "HVAC", name_en: "Split AC 1 Ton", name_ar: "مكيف سبليت 1 طن", min_w: 1200, max_w: 1500, hours: 8.0, default_qty: 1, desc_en: "Suitable for small bedrooms (up to 12 sqm)", desc_ar: "مناسب لغرف النوم الصغيرة (حتى 12 متر مربع)", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "ac_1_5ton", property_type: "residential", category: "HVAC", name_en: "Split AC 1.5 Ton", name_ar: "مكيف سبليت 1.5 طن", min_w: 1800, max_w: 2200, hours: 8.0, default_qty: 0, desc_en: "Suitable for medium bedrooms (up to 18 sqm)", desc_ar: "مناسب لغرف النوم المتوسطة (حتى 18 متر مربع)", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "ac_2ton", property_type: "residential", category: "HVAC", name_en: "Split AC 2 Ton", name_ar: "مكيف سبليت 2 طن", min_w: 2400, max_w: 3000, hours: 8.0, default_qty: 1, desc_en: "Suitable for large living rooms/halls", desc_ar: "مناسب للصالات وغرف المعيشة الكبيرة", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "refrigerator", property_type: "residential", category: "Kitchen", name_en: "Refrigerator", name_ar: "ثلاجة", min_w: 150, max_w: 300, hours: 24.0, default_qty: 1, desc_en: "Always-on kitchen food refrigeration", desc_ar: "ثلاجة المطبخ لحفظ الأطعمة على مدار الساعة", cat_en: "Kitchen", cat_ar: "المطبخ" },
    { id: "freezer", property_type: "residential", category: "Kitchen", name_en: "Freezer", name_ar: "فريزر", min_w: 200, max_w: 400, hours: 24.0, default_qty: 0, desc_en: "Dedicated food freezing unit", desc_ar: "وحدة تجميد الأطعمة المخصصة", cat_en: "Kitchen", cat_ar: "المطبخ" },
    { id: "washing_machine", property_type: "residential", category: "Kitchen", name_en: "Washing Machine", name_ar: "غسالة ملابس", min_w: 500, max_w: 1000, hours: 1.0, default_qty: 0, desc_en: "Automatic clothes washing appliance", desc_ar: "غسالة الملابس الأوتوماتيكية القياسية", cat_en: "Laundry", cat_ar: "الغسيل" },
    { id: "water_heater", property_type: "residential", category: "HVAC", name_en: "Water Heater", name_ar: "سخان مياه", min_w: 1500, max_w: 2000, hours: 3.0, default_qty: 0, desc_en: "Bathroom & kitchen hot water system", desc_ar: "سخان المياه الساخنة للحمام والمطبخ", cat_en: "Utility", cat_ar: "المرافق" },
    { id: "tv", property_type: "residential", category: "General", name_en: "TV", name_ar: "تلفاز", min_w: 80, max_w: 150, hours: 6.0, default_qty: 1, desc_en: "Living room media display screen", desc_ar: "شاشة عرض التلفاز لغرفة المعيشة", cat_en: "Entertainment", cat_ar: "الترفيه" },
    { id: "led_lights", property_type: "residential", category: "General", name_en: "LED Lights (Set of 10)", name_ar: "أضواء LED (طقم 10)", min_w: 50, max_w: 100, hours: 6.0, default_qty: 1, desc_en: "Energy-efficient home light bulbs", desc_ar: "مصابيح إضاءة منزلية موفرة للطاقة", cat_en: "Lighting", cat_ar: "الإضاءة" },
    { id: "ceiling_fan", property_type: "residential", category: "HVAC", name_en: "Ceiling Fan", name_ar: "مروحة سقف", min_w: 50, max_w: 80, hours: 12.0, default_qty: 0, desc_en: "Standard overhead air circulator", desc_ar: "مروحة سقف دائرية قياسية لتحريك الهواء", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "microwave", property_type: "residential", category: "Kitchen", name_en: "Microwave", name_ar: "مايكروويف", min_w: 1000, max_w: 1500, hours: 0.5, default_qty: 0, desc_en: "Kitchen countertop reheating appliance", desc_ar: "جهاز تسخين الوجبات السريع للمطبخ", cat_en: "Kitchen", cat_ar: "المطبخ" },
    { id: "electric_oven", property_type: "residential", category: "Kitchen", name_en: "Electric Oven", name_ar: "فرن كهربائي", min_w: 2000, max_w: 3000, hours: 1.0, default_qty: 0, desc_en: "Baking and heavy cooking oven", desc_ar: "فرن طهي وخبز كهربائي عالي القدرة", cat_en: "Kitchen", cat_ar: "المطبخ" },
    { id: "water_pump", property_type: "residential", category: "Luxury", name_en: "Water Pump", name_ar: "مضخة مياه", min_w: 750, max_w: 1500, hours: 2.0, default_qty: 0, desc_en: "Rooftop water pressurization system", desc_ar: "مضخة ضغط مياه الخزان العلوي", cat_en: "Utility", cat_ar: "المرافق" },
    { id: "dishwasher", property_type: "residential", category: "Kitchen", name_en: "Dishwasher", name_ar: "غسالة صحون", min_w: 1200, max_w: 1800, hours: 1.0, default_qty: 0, desc_en: "Automatic kitchen dish washing unit", desc_ar: "غسالة صحون أوتوماتيكية للمطبخ", cat_en: "Kitchen", cat_ar: "المطبخ" },
    { id: "desktop_pc", property_type: "residential", category: "General", name_en: "Desktop PC", name_ar: "كمبيوتر مكتبي", min_w: 150, max_w: 300, hours: 4.0, default_qty: 0, desc_en: "Standard desktop computer station", desc_ar: "كمبيوتر مكتبي مع شاشته وملحقاته", cat_en: "General", cat_ar: "عام" },
    { id: "laptop", property_type: "residential", category: "General", name_en: "Laptop", name_ar: "كمبيوتر محمول", min_w: 50, max_w: 90, hours: 6.0, default_qty: 0, desc_en: "Personal computer and device charger", desc_ar: "كمبيوتر محمول شخصي لشحن الأجهزة والعمل", cat_en: "General", cat_ar: "عام" },
    { id: "ev_charger", property_type: "residential", category: "Luxury", name_en: "EV Charger", name_ar: "شاحن سيارة كهربائية", min_w: 3600, max_w: 7200, hours: 4.0, default_qty: 0, desc_en: "Residential electric vehicle charging", desc_ar: "شاحن منزلي مخصص للسيارات الكهربائية", cat_en: "Utility", cat_ar: "المرافق" },
    { id: "com_ducted_ac", property_type: "commercial", category: "HVAC", name_en: "Commercial Ducted AC", name_ar: "مكيف تجاري مركزي", min_w: 4000, max_w: 6000, hours: 11.0, default_qty: 1, desc_en: "Ducted cooling for business spaces", desc_ar: "مكيف مركزي تجاري للمحلات والمكاتب", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "com_server_rack", property_type: "commercial", category: "IT", name_en: "Network Rack Server", name_ar: "خادم شبكة", min_w: 500, max_w: 1200, hours: 24.0, default_qty: 0, desc_en: "Active business servers running 24/7", desc_ar: "خوادم شبكية تعمل باستمرار لقطاع الأعمال", cat_en: "IT", cat_ar: "تقنية المعلومات" },
    { id: "com_led_lighting", property_type: "commercial", category: "Lighting", name_en: "Commercial LED Panel Set", name_ar: "إضاءة LED تجارية", min_w: 1500, max_w: 1500, hours: 11.0, default_qty: 1, desc_en: "Office/retail high efficiency lighting", desc_ar: "مصابيح إضاءة تجارية عالية الكفاءة للمكتب", cat_en: "Lighting", cat_ar: "الإضاءة" },
    { id: "com_copier", property_type: "commercial", category: "Office", name_en: "Office Copier & Printer", name_ar: "طابعة ومصورة مكتبية", min_w: 750, max_w: 750, hours: 3.0, default_qty: 0, desc_en: "Multifunction document processing", desc_ar: "طابعة ومصورة وثائق مكتبية متعددة الوظائف", cat_en: "Office", cat_ar: "المكتب" },
    { id: "com_display_fridge", property_type: "commercial", category: "Cooling", name_en: "Commercial Display Fridge", name_ar: "ثلاجة عرض تجارية", min_w: 800, max_w: 1200, hours: 24.0, default_qty: 1, desc_en: "Glass showcase beverage cooler", desc_ar: "ثلاجة عرض زجاجية للأطعمة والمشروبات", cat_en: "Cooling", cat_ar: "التبريد" },
    { id: "com_cctv", property_type: "commercial", category: "Security", name_en: "CCTV Security System", name_ar: "نظام مراقبة CCTV", min_w: 200, max_w: 400, hours: 24.0, default_qty: 1, desc_en: "Continuous camera monitoring & NVR", desc_ar: "نظام مراقبة أمني بالكاميرات مع جهاز تسجيل", cat_en: "Security", cat_ar: "الأمن" },
    { id: "com_workstation", property_type: "commercial", category: "Office", name_en: "Desktop Workstation", name_ar: "محطة عمل مكتبية", min_w: 200, max_w: 200, hours: 8.0, default_qty: 2, desc_en: "Desktop computer for office staff", desc_ar: "جهاز كمبيوتر مكتبي لموظفي الشركة", cat_en: "Office", cat_ar: "المكتب" },
    { id: "com_water_dispenser", property_type: "commercial", category: "Kitchen", name_en: "Commercial Water Dispenser", name_ar: "موزع مياه تجاري", min_w: 500, max_w: 500, hours: 10.0, default_qty: 0, desc_en: "Office hot/cold water supply", desc_ar: "موزع مياه باردة وساخنة للموظفين والعملاء", cat_en: "Office", cat_ar: "المكتب" },
    { id: "com_sliding_door", property_type: "commercial", category: "General", name_en: "Auto Sliding Doors", name_ar: "أبواب منزلقة تلقائية", min_w: 150, max_w: 150, hours: 11.0, default_qty: 0, desc_en: "Electronic motion-sensing entrance", desc_ar: "مدخل أبواب زجاجية منزلقة تعمل بالحساسات", cat_en: "General", cat_ar: "عام" },
    { id: "com_adv_signage", property_type: "commercial", category: "Lighting", name_en: "LED Advertising Signage", name_ar: "لوحة إعلانية LED", min_w: 300, max_w: 800, hours: 11.0, default_qty: 0, desc_en: "Illuminated storefront brand display", desc_ar: "لوحة إعلانية مضيئة للعلامة التجارية بالخارج", cat_en: "Lighting", cat_ar: "الإضاءة" },
    { id: "ind_compressor", property_type: "industrial", category: "Machinery", name_en: "Industrial Air Compressor", name_ar: "ضاغط هواء صناعي", min_w: 15000, max_w: 37000, hours: 12.0, default_qty: 1, desc_en: "Heavy power plant pneumatic air supply", desc_ar: "ضاغط هواء صناعي عالي الطاقة للعمليات", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_chiller", property_type: "industrial", category: "Cooling", name_en: "Industrial Water Chiller", name_ar: "مبرد مياه صناعي", min_w: 50000, max_w: 150000, hours: 20.0, default_qty: 0, desc_en: "Water-cooled fluid process chiller", desc_ar: "مبرد سوائل صناعي ضخم لتبريد الآلات", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_water_pump", property_type: "industrial", category: "Machinery", name_en: "Three-Phase Water Pump", name_ar: "مضخة مياه ثلاثية الطور", min_w: 15000, max_w: 15000, hours: 8.0, default_qty: 1, desc_en: "High-volume process pump (20 HP)", desc_ar: "مضخة مياه وتصريف للمنشآت بقوة 20 حصان", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_molding_mach", property_type: "industrial", category: "Machinery", name_en: "Injection Molding Machine", name_ar: "آلة حقن وتشكيل البلاستيك", min_w: 30000, max_w: 75000, hours: 20.0, default_qty: 0, desc_en: "Automated custom parts manufacturing", desc_ar: "آلة حقن أوتوماتيكية لتصنيع قطع البلاستيك", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_gantry_crane", property_type: "industrial", category: "Machinery", name_en: "Overhead Gantry Crane", name_ar: "رافعة علوية صناعية", min_w: 5000, max_w: 15000, hours: 3.0, default_qty: 0, desc_en: "Heavy equipment plant room hoisting", desc_ar: "رافعة جسرية علوية لنقل الأوزان الثقيلة", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_exhaust_fan", property_type: "industrial", category: "Ventilation", name_en: "Industrial Exhaust Fan", name_ar: "مروحة سحب صناعية", min_w: 3000, max_w: 7500, hours: 18.0, default_qty: 2, desc_en: "High volume warehouse air extraction", desc_ar: "مروحة سحب وتفريغ الهواء للتهوية في المصنع", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_welding_mach", property_type: "industrial", category: "Machinery", name_en: "Industrial Welder Station", name_ar: "محطة لحام صناعية", min_w: 8000, max_w: 12000, hours: 5.0, default_qty: 0, desc_en: "Heavy-duty manufacturing metal welder", desc_ar: "آلة لحام صناعية ثقيلة للأعمال المعدنية", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_conveyor", property_type: "industrial", category: "Machinery", name_en: "Assembly Line Conveyor", name_ar: "سير ناقل صناعي", min_w: 4000, max_w: 11000, hours: 12.0, default_qty: 1, desc_en: "Automated factory assembly transport", desc_ar: "نظام سير ناقل لخطوط التجميع والتغليف", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_cnc_machine", property_type: "industrial", category: "Machinery", name_en: "CNC Milling Machine", name_ar: "آلة تشكيل بالتحكم الرقمي", min_w: 11000, max_w: 22000, hours: 10.0, default_qty: 0, desc_en: "Precision automated metal lathe", desc_ar: "آلة تشكيل وخراطة دقيقة تعمل بالكمبيوتر", cat_en: "Factory", cat_ar: "المصنع" },
    { id: "ind_induction_furnace", property_type: "industrial", category: "Machinery", name_en: "Induction Furnace", name_ar: "فرن حثي صهر المعادن", min_w: 50000, max_w: 100000, hours: 8.0, default_qty: 0, desc_en: "Metal smelting induction furnace", desc_ar: "فرن حثي حراري مخصص لصهر المعادن", cat_en: "Factory", cat_ar: "المصنع" }
  ];
"""
    updated_content = content[:start_idx] + new_appliances + content[end_idx:]
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(updated_content)
    print("SUCCESS: Updated APPLIANCES array in calculator-engine.js")
else:
    print(f"ERROR: Indices not found. start={start_idx}, end={end_idx}")
